### ISSUE TITLE
Colombia - Preparar dados de IGAC, Bogota e Medellin

### ISSUE THREAD

**Issue by ThierryAJean** [AddressForAll/digital-preservation-CO#2]
PRecisamos preparar um pouco os dados da Colombia para MS.

**Comment by ppKrauss** [comment]
A partir desta semana o Igor estará distribuindo tarefas de análise e inclusão na Preservação Digital para o Carlos. Entre os dados repassados estarão os packages da Colômbia.  Se for necessário eu ajudo Carlos a revisar e montar os primeiros templates para makefiles CO.

**Comment by ThierryAJean** [comment]
@crebollobr me diz que a adição destas parcelas dependem do @ppKrauss .

**Comment by ThierryAJean** [comment]
O servidor não consegue importar os lotes/parcels. @ppkrauss deve ajudar.@0e1 deve ajudar
