### ISSUE TITLE
Rever o REPORT OF FILTERED DATA 2021-08

### ISSUE THREAD

**Issue by ThierryAJean** [AddressForAll/digital-preservation-CO#3]

**Comment by IgorEliezer** [comment]
Resolvido hoje na videoconf com Carlos e Peter.

**Comment by IgorEliezer** [comment]
Também renomeamos e aprimoramos a classificação e descrição dos tipos de objetos (feature name) que delimitam áreas com nome (município; distrito; bairro; loteamento; condomínio; ilha) no documento "Estrutura dos dados recebidos pelo Instituto AddressForAll".
